var phonicData ={ 
    "round1":{
        "randomSound":{
            "phonic1":{
                "sound":"a.mp3",
                "correctAnswer":"a"
            },
            "phonic2":{
                "sound":"i.mp3",
                "correctAnswer":"i"
            },
            "phonic3":{
                "sound":"n.mp3",
                "correctAnswer":"n"
            },
            "phonic4":{
                "sound":"p.mp3",
                "correctAnswer":"p"
            },
            "phonic5":{
                "sound":"s.mp3",
                "correctAnswer":"s"
            },
            "phonic6":{
                "sound":"t.mp3",
                "correctAnswer":"t"
            } 
        },
        "choices":["a", "i", "n", "p", "s", "t"]
    },
    "round2":{
        "randomSound":{
            "phonic1":{
                "sound":"ck.mp3",
                "correctAnswer":"ck"
            },
            "phonic2":{
                "sound":"d.mp3",
                "correctAnswer":"d"
            },
            "phonic3":{
                "sound":"e.mp3",
                "correctAnswer":"e"
            },
            "phonic4":{
                "sound":"h.mp3",
                "correctAnswer":"h"
            },
            "phonic5":{
                "sound":"m.mp3",
                "correctAnswer":"m"
            },
            "phonic6":{
                "sound":"r.mp3",
                "correctAnswer":"r"
            } 
        },
        "choices":["ck", "d", "e", "h", "m", "r"]
    },
    "round3":{
        "randomSound":{
            "phonic1":{
                "sound":"b.mp3",
                "correctAnswer":"b"
            },
            "phonic2":{
                "sound":"f.mp3",
                "correctAnswer":"f"
            },
            "phonic3":{
                "sound":"g.mp3",
                "correctAnswer":"g"
            },
            "phonic4":{
                "sound":"l.mp3",
                "correctAnswer":"l"
            },
            "phonic5":{
                "sound":"o.mp3",
                "correctAnswer":"o"
            },
            "phonic6":{
                "sound":"u.mp3",
                "correctAnswer":"u"
            } 
        },
        "choices":["b", "f", "g", "l", "o", "u"]
    },
    "round4":{
        "randomSound":{
            "phonic1":{
                "sound":"ai.mp3",
                "correctAnswer":"ai"
            },
            "phonic2":{
                "sound":"ee.mp3",
                "correctAnswer":"ee"
            },
            "phonic3":{
                "sound":"ie.mp3",
                "correctAnswer":"e"
            },
            "phonic4":{
                "sound":"j.mp3",
                "correctAnswer":"j"
            },
            "phonic5":{
                "sound":"oa.mp3",
                "correctAnswer":"oa"
            },
            "phonic6":{
                "sound":"or.mp3",
                "correctAnswer":"or"
            } 
        },
        "choices":["ai", "ee", "ie", "j", "oa", "or"]
    },
    "round5":{
        "randomSound":{
            "phonic1":{
                "sound":"book.mp3",
                "correctAnswer":"book"
            },
            "phonic2":{
                "sound":"moon.mp3",
                "correctAnswer":"moon"
            },
            "phonic3":{
                "sound":"ng.mp3",
                "correctAnswer":"ng"
            },
            "phonic4":{
                "sound":"v.mp3",
                "correctAnswer":"v"
            },
            "phonic5":{
                "sound":"w.mp3",
                "correctAnswer":"w"
            },
            "phonic6":{
                "sound":"z.mp3",
                "correctAnswer":"z"
            } 
        },
        "choices":["book", "moon", "ng", "v", "w", "z"]
    },
    "round6":{
        "randomSound":{
            "phonic1":{
                "sound":"ch.mp3",
                "correctAnswer":"ch"
            },
            "phonic2":{
                "sound":"sh.mp3",
                "correctAnswer":"sh"
            },
            "phonic3":{
                "sound":"this.mp3",
                "correctAnswer":"this"
            },
            "phonic4":{
                "sound":"three.mp3",
                "correctAnswer":"three"
            },
            "phonic5":{
                "sound":"x.mp3",
                "correctAnswer":"x"
            },
            "phonic6":{
                "sound":"y.mp3",
                "correctAnswer":"y"
            } 
        },
        "choices":["ch", "sh", "this", "three", "x", "y"]
    },
    "round7":{
        "randomSound":{
            "phonic1":{
                "sound":"ar.mp3",
                "correctAnswer":"ar"
            },
            "phonic2":{
                "sound":"er.mp3",
                "correctAnswer":"er"
            },
            "phonic3":{
                "sound":"oi.mp3",
                "correctAnswer":"oi"
            },
            "phonic4":{
                "sound":"ou.mp3",
                "correctAnswer":"ou"
            },
            "phonic5":{
                "sound":"qu.mp3",
                "correctAnswer":"qu"
            },
            "phonic6":{
                "sound":"ue.mp3",
                "correctAnswer":"ue"
            } 
        },
        "choices":["ar", "er", "oi", "ou", "qu", "ue"]
    } 
};


